Repository trimstray/htrace.sh, pull requests merged in 2019-03, with the labels that each got.

#49 fixed link
  CONTRIBUTING.md
Labels: Priority: Low, Status: Review Needed, Type: Bug

#51 Fix README.md
  README.md
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#48 Get htrace.sh to work in macOS
  README.md
  bin/htrace.sh
  setup.sh
Labels: Priority: Critical, Status: Review Needed, Type: Feature

#55 Fix docker build
  README.md
  bin/htrace.sh
  build/Dockerfile
  build/build.sh
  setup.sh
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#59 Work with LibreSSL in addition to OpenSSL
  src/__init__
Labels: Priority: Medium, Status: Review Needed, Type: Feature

#63 Fix for issue #60
  build/Dockerfile
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#77 Update DomainCertCheck
  lib/DomainCertCheck
Labels: Priority: Medium, Status: In Progress, Type: Bug, v1.1.4
